// <auto-generated />
namespace DataAccessLayer.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class dok_has_guncelleme : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(dok_has_guncelleme));
        
        string IMigrationMetadata.Id
        {
            get { return "202210181151556_dok_has_guncelleme"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
